language: android
jdk: oraclejdk8

os:
  - linux
dist: xenial

addons:
  apt_packages:
    - pandoc
before_install:
  - yes | $ANDROID_HOME/tools/bin/sdkmanager "platforms;android-30"
  - chmod +x gradlew
android:
  components:
    - tools
    - platform-tools
    - tools
    - build-tools-30.0.2
    - android-30
  licenses:
    - android-sdk-preview-license-.+
    - android-sdk-license-.+
    - google-gdk-license-.+

script:
  - ./gradlew clean check --profile
  - pandoc `ls -1rt build/reports/profile/profile-*.html | tail -n1` -t plain
  - ./gradlew build
  - ./gradlew test
